# Generated by Django 5.0.6 on 2024-09-02 06:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
