# Generated by Django 5.0.6 on 2024-09-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Label',
        ),
    ]
