# Generated by Django 4.2.11 on 2025-01-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
