# Generated by Django 4.2.11 on 2025-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
